#server:
#  port: 19020
#
#spring:
#  application:
#    name: restaurant-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/restaurant_db
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      username: default
#      password: password
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      format-sql: true
#      use_sql_comments: true
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:19000/eureka/
#
#
#
#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0
#
#  #모든 엔드포인트 노출 설정
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    #헬스 체크 엔드포인트 상세 정보 표시 설정
#    health:
#      show-details: always
#
#  #프로메테우스 사용활성화
#  metrics:
#    export:
#      prometheus:
#        enabled: true
